version: '3.8'

services:
  dnsmasq-manager:
    build: .
    container_name: dnsmasq-manager
    ports:
      - "3000:3000"
    environment:
      - DNSMASQ_HOSTS=/app/data/extra_hosts.conf
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    privileged: true  # Required for dnsmasq to bind to port 53
    networks:
      - dnsmasq-network

networks:
  dnsmasq-network:
    driver: bridge
